#!/usr/bin/env python3
"""Q20 case table and input writers for GS2 8.2.1 and stella v1.0.

    python cases.py write <root> [pattern ...]   write <root>/<code>/<case>/<case>.in for matching cases
    python cases.py list [pattern ...]           print case name, code, ky_gs2, t_max, nstep

Every number is in the codes' own units: Lref as stated per physics set, vref = sqrt(2T/m),
so ky_gs2 = sqrt(2) * ky_gx (see manifest.toml [normalization]).
"""

from __future__ import annotations

import fnmatch
import math
import sys
from pathlib import Path

SQRT2 = math.sqrt(2.0)
KY_GX = [0.15, 0.30, 0.40, 0.50, 0.55]
R_OVER_A = 2.77778

PHYS = {
    # Lref = a (GX deck)
    "a": dict(tprim=2.49, fprim=0.8, q=1.4),
    # Lref = R (GS2 shipped cyclone_itg; stella install cross-check)
    "R": dict(tprim=6.9, fprim=2.2, q=2.0 / 1.44),
}

GS2_RUNGS = {
    "r1": dict(ntheta=16, nperiod=2, negrid=8, ngauss=4, delt=0.05),
    "r2": dict(ntheta=32, nperiod=2, negrid=12, ngauss=6, delt=0.05),
    "r3": dict(ntheta=48, nperiod=3, negrid=16, ngauss=8, delt=0.025),
    "r4": dict(ntheta=64, nperiod=4, negrid=24, ngauss=12, delt=0.025),
    "shipped": dict(ntheta=12, nperiod=1, negrid=12, ngauss=3, delt=0.05),
}
STELLA_RUNGS = {
    "r1": dict(nzed=24, nperiod=2, nvgrid=12, nmu=6, delt=0.02),
    "r2": dict(nzed=48, nperiod=2, nvgrid=24, nmu=12, delt=0.02),
    "r3": dict(nzed=64, nperiod=3, nvgrid=32, nmu=16, delt=0.02),
    "r4": dict(nzed=96, nperiod=4, nvgrid=48, nmu=24, delt=0.01),
    "install": dict(nzed=48, nperiod=1, nvgrid=24, nmu=12, delt=0.02),
}

# t_max in the codes' own time unit (Lref/vref); chosen for >= ~10 e-folds at the expected gamma.
T_MAX_A = {
    "S": {0.15: 600.0, 0.30: 400.0, 0.40: 400.0, 0.50: 600.0, 0.55: 1200.0},
    "M": {0.15: 400.0, 0.30: 300.0, 0.40: 300.0, 0.50: 300.0, 0.55: 300.0},
}
T_MAX_R = 150.0  # Lref = R: gamma_gs2 ~ 0.17-0.37 at ky_gs2 = 0.5


def geometry_gs2(geom: str, phys: str, ntheta: int, nperiod: int) -> str:
    q = PHYS[phys]["q"]
    if geom == "S":
        # Lref = a: epsl = 2a/R, pk = 2a/(qR); Lref = R: epsl = 2, pk = 2/q.
        lr = 1.0 / R_OVER_A if phys == "a" else 1.0
        epsl = 2.0 * lr
        pk = epsl / q
        return f"""&theta_grid_parameters
 ntheta = {ntheta}
 nperiod = {nperiod}
 eps = 0.18
 epsl = {epsl:.10f}
 shat = 0.8
 pk = {pk:.10f}
 shift = 0.0
/
&theta_grid_knobs
 equilibrium_option = "s-alpha"
/
&theta_grid_salpha_knobs
 model_option = "default"
/
"""
    rhoc, rmaj = (0.5, R_OVER_A) if phys == "a" else (0.18, 1.0)
    return f"""&theta_grid_parameters
 ntheta = {ntheta}
 nperiod = {nperiod}
 rhoc = {rhoc}
 qinp = {q:.10f}
 shat = 0.8
 rmaj = {rmaj}
 r_geo = {rmaj}
 shift = 0.0
 akappa = 1.0
 akappri = 0.0
 tri = 0.0
 tripri = 0.0
/
&theta_grid_knobs
 equilibrium_option = "eik"
/
&theta_grid_eik_knobs
 itor = 1
 iflux = 0
 irho = 2
 local_eq = .true.
 bishop = 4
 s_hat_input = 0.8
 beta_prime_input = 0.0
 delrho = 1.0e-3
 isym = 0
 ppl_eq = .false.
 gen_eq = .false.
 efit_eq = .false.
 equal_arc = .true.
 writelots = .false.
/
"""


def gs2_input(case: dict) -> str:
    r = dict(GS2_RUNGS[case["rung"]])
    r.update(case.get("override", {}))
    phys = PHYS[case["phys"]]
    nstep = int(round(case["t_max"] / r["delt"]))
    nwrite = max(1, nstep // 600)
    fexpr = case.get("fexpr", 0.48)
    return f"""! Q20 {case["name"]} (generated by cases.py)
&kt_grids_knobs
 grid_option = "single"
/
&kt_grids_single_parameters
 aky = {case["ky_code"]:.10f}
 theta0 = 0.0
/
{geometry_gs2(case["geom"], case["phys"], r["ntheta"], r["nperiod"])}&le_grids_knobs
 ngauss = {r["ngauss"]}
 negrid = {r["negrid"]}
/
&dist_fn_knobs
 gridfac = 1.0
 omprimfac = 1.0
 boundary_option = "linked"
 adiabatic_option = "iphi00=2"
 g_exb = 0.0
 nonad_zero = .true.
/
&fields_knobs
 field_option = "local"
/
&layouts_knobs
 layout = "lexys"
/
&knobs
 beta = 0.0
 zeff = 1.0
 wstar_units = .false.
 fphi = 1.0
 fapar = 0.0
 fbpar = 0.0
 delt = {r["delt"]}
 nstep = {nstep}
/
&reinit_knobs
 delt_adj = 2.0
 delt_minimum = 1.0e-06
/
&collisions_knobs
 collision_model = "none"
/
&nonlinear_terms_knobs
 nonlinear_mode = "off"
/
&species_knobs
 nspec = 1
/
&species_parameters_1
 z = 1.0
 mass = 1.0
 dens = 1.0
 temp = 1.0
 tprim = {phys["tprim"]}
 fprim = {phys["fprim"]}
 uprim = 0.0
 vnewk = 0.0
 type = "ion"
/
&dist_fn_species_knobs_1
 fexpr = {fexpr}
 bakdif = 0.05
/
&init_g_knobs
 chop_side = .false.
 phiinit = 0.001
 ginit_option = "noise"
 constant_random_flag = .true.
/
&gs2_diagnostics_knobs
 write_ascii = .false.
 print_flux_line = .false.
 write_fluxes = .false.
 print_line = .false.
 write_verr = .false.
 write_line = .false.
 write_heating = .false.
 write_avg_moments = .false.
 write_omega = .true.
 write_omavg = .false.
 write_eigenfunc = .false.
 write_final_fields = .true.
 write_final_moments = .false.
 nsave = -1
 nwrite = {nwrite}
 navg = 10
 omegatol = -0.001
 omegatinst = 500.0
 save_for_restart = .false.
 write_phi_over_time = .false.
/
"""


def stella_input(case: dict) -> str:
    r = dict(STELLA_RUNGS[case["rung"]])
    r.update(case.get("override", {}))
    phys = PHYS[case["phys"]]
    rhoc, rmaj = (0.5, R_OVER_A) if case["phys"] == "a" else (0.18, 1.0)
    nstep = int(round(case["t_max"] / r["delt"]))
    nwrite = max(1, nstep // 600)
    return f"""! Q20 {case["name"]} (generated by cases.py)
&geometry_options
  geometry_option = "miller"
/
&geometry_miller
  nzed_local = 128
  rhoc = {rhoc}
  shat = 0.8
  qinp = {phys["q"]:.10f}
  rmaj = {rmaj}
  rgeo = {rmaj}
  shift = 0.0
  kappa = 1.0
  kapprim = 0.0
  tri = 0.0
  triprim = 0.0
  betaprim = 0.0
  d2qdr2 = 0.0
  d2psidr2 = 0.0
  betadbprim = 0.0
/
&gyrokinetic_terms
  include_parallel_streaming = .true.
  include_mirror = .true.
  include_xdrift = .true.
  include_ydrift = .true.
  include_drive = .true.
  include_nonlinear = .false.
/
&adiabatic_electron_response
  adiabatic_option = "field-line-average-term"
  tite = 1.0
  nine = 1.0
/
&species_options
  nspec = 1
/
&species_parameters_1
  dens = 1.0
  fprim = {phys["fprim"]}
  mass = 1.0
  temp = 1.0
  tprim = {phys["tprim"]}
  type = "ion"
  z = 1.0
/
&kxky_grid_option
  grid_option = "range"
/
&kxky_grid_range
  naky = 1
  aky_min = {case["ky_code"]:.10f}
  aky_max = {case["ky_code"]:.10f}
  nakx = 1
  akx_min = 0.0
  akx_max = 0.0
/
&z_grid
  nzed = {r["nzed"]}
  nperiod = {r["nperiod"]}
/
&z_boundary_condition
  boundary_option = "linked"
/
&velocity_grids
  nmu = {r["nmu"]}
  nvgrid = {r["nvgrid"]}
  vpa_max = 3.0
/
&diagnostics
  nwrite = {nwrite}
  nsave = -1
/
&diagnostics_omega
  write_omega_vs_kxky = .true.
  write_omega_avg_vs_kxky = .true.
/
&initialise_distribution
  initialise_distribution_option = "default"
  phiinit = 0.01
/
&time_trace_options
  nstep = {nstep}
  autostop = .false.
/
&time_step
  delt = {r["delt"]}
/
&numerical_algorithms
  explicit_algorithm = "rk2"
  stream_implicit = .true.
  mirror_implicit = .true.
  drifts_implicit = .false.
/
"""


def all_cases() -> list[dict]:
    cases: list[dict] = []
    for geom, codes in (("S", ["gs2"]), ("M", ["gs2", "stella"])):
        for code in codes:
            for rung in ("r1", "r2", "r3", "r4"):
                for ky in KY_GX:
                    cases.append(
                        dict(
                            name=f"{code}_{geom}_ky{ky:.2f}_{rung}",
                            code=code,
                            geom=geom,
                            phys="a",
                            rung=rung,
                            ky_gx=ky,
                            ky_code=SQRT2 * ky,
                            t_max=T_MAX_A[geom][ky],
                        )
                    )
    # gap decomposition, Lref = R, ky_gs2 = 0.5 (ky_gx = 0.3536)
    g = dict(phys="R", ky_code=0.5, ky_gx=0.5 / SQRT2, t_max=T_MAX_R)
    cases.append(
        dict(
            name="G1_gs2_S_shipped_fexpr0.45",
            code="gs2",
            geom="S",
            rung="shipped",
            fexpr=0.45,
            **g,
        )
    )
    cases.append(
        dict(
            name="G1_gs2_S_shipped_fexpr0.48", code="gs2", geom="S", rung="shipped", **g
        )
    )
    for rung in ("r2", "r3"):
        cases.append(
            dict(name=f"G2_gs2_S_{rung}", code="gs2", geom="S", rung=rung, **g)
        )
        cases.append(
            dict(name=f"G3_gs2_M18_{rung}", code="gs2", geom="M", rung=rung, **g)
        )
    for rung in ("install", "r2", "r3"):
        cases.append(
            dict(name=f"G4_stella_M18_{rung}", code="stella", geom="M", rung=rung, **g)
        )
    return cases


def select(patterns: list[str]) -> list[dict]:
    cases = all_cases()
    if not patterns:
        return cases
    return [c for c in cases if any(fnmatch.fnmatch(c["name"], p) for p in patterns)]


def main() -> None:
    cmd = sys.argv[1]
    if cmd == "list":
        for c in select(sys.argv[2:]):
            rung = (GS2_RUNGS if c["code"] == "gs2" else STELLA_RUNGS)[c["rung"]]
            print(
                c["name"],
                c["code"],
                f"{c['ky_code']:.5f}",
                c["t_max"],
                int(round(c["t_max"] / rung["delt"])),
            )
    elif cmd == "write":
        root = Path(sys.argv[2])
        for c in select(sys.argv[3:]):
            d = root / c["code"] / c["name"]
            d.mkdir(parents=True, exist_ok=True)
            text = gs2_input(c) if c["code"] == "gs2" else stella_input(c)
            (d / f"{c['name']}.in").write_text(text)
            print(c["code"], c["name"])
    else:
        raise SystemExit(__doc__)


if __name__ == "__main__":
    main()
