"""Render the ledger section of ``docs/verification_matrix.rst``.

``tools/evidence_ledger.toml`` is the single index of public claims. This
script writes its rows, statuses, parity numbers and velocity-space
declarations into the block of ``docs/verification_matrix.rst`` between the
``BEGIN``/``END`` markers, so the page cannot disagree with the ledger.

    python scripts/validation_matrix.py           # rewrite the block
    python scripts/validation_matrix.py --check   # exit 1 if the block is stale

Parity percentages are recomputed from each row's artifact with the formula
``tests/release/test_evidence_ledger.py`` uses for the README table:
``100 * max|gkx - ref| / max|ref|`` over the tracked scan.
"""

from __future__ import annotations

import argparse
import csv
import sys
import tomllib
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
LEDGER = ROOT / "tools" / "evidence_ledger.toml"
PAGE = ROOT / "docs" / "verification_matrix.rst"
BEGIN = (
    ".. BEGIN LEDGER MATRIX (generated by scripts/validation_matrix.py; do not edit)"
)
END = ".. END LEDGER MATRIX"

RANKS = {
    1: "analytic",
    2: "published",
    3: "reference-code golden",
    4: "open dataset",
    5: "self-run",
}
STATUS_ORDER = ("failing", "provisional", "open", "passing", "superseded")


def _peak_relative_percent(rows: list[dict[str, str]], ref: str, gkx: str) -> float:
    ref_values = [float(row[ref]) for row in rows]
    gkx_values = [float(row[gkx]) for row in rows]
    peak = max(abs(value) for value in ref_values)
    worst = max(abs(a - b) for a, b in zip(ref_values, gkx_values))
    return 100.0 * worst / peak


def _percent(value: float) -> str:
    """Round like the README table: three figures, two below 0.1, one below 1e-3."""

    if value >= 0.1:
        return f"{value:#.3g}%"
    if value >= 1e-3:
        return f"{value:#.2g}%"
    return f"{value:.1g}%"


def _measured(row: dict, root: Path) -> str:
    columns = row.get("columns")
    if not columns:
        return _escape(row["observable"])
    with (root / row["artifact"]).open(encoding="utf-8") as handle:
        rows = list(csv.DictReader(handle))
    gamma = _peak_relative_percent(rows, columns["gamma_ref"], columns["gamma_gkx"])
    omega = _peak_relative_percent(rows, columns["omega_ref"], columns["omega_gkx"])
    return f"gamma {_percent(gamma)}, omega {_percent(omega)}"


def _cell(text: str) -> str:
    """Flatten a cell onto one line."""

    return " ".join(text.split())


def _escape(text: str) -> str:
    """Quote free ledger text so reST reads no inline markup in it."""

    for char in ("\\", "*", "`", "|", "_"):
        text = text.replace(char, "\\" + char)
    return _cell(text)


def _table(
    header: tuple[str, ...], widths: str, body: list[tuple[str, ...]]
) -> list[str]:
    lines = [".. list-table::", "   :header-rows: 1", f"   :widths: {widths}", ""]
    for cells in (header, *body):
        lines.append(f"   * - {_cell(cells[0])}")
        lines.extend(f"     - {_cell(cell)}" for cell in cells[1:])
    return [*lines, ""]


def render(ledger_path: Path = LEDGER, root: Path = ROOT) -> str:
    """Return the generated block, markers included."""

    ledger = tomllib.loads(ledger_path.read_text(encoding="utf-8"))
    rows = ledger["row"]
    counts = {
        status: sum(row["status"] == status for row in rows) for status in STATUS_ORDER
    }
    summary = ", ".join(f"{n} {status}" for status, n in counts.items() if n)
    out = [
        BEGIN,
        "",
        f"Ledger ``tools/evidence_ledger.toml``, schema {ledger['schema_version']}, "
        f"updated {ledger['updated']}: {len(rows)} rows, {summary}.",
        "",
        "Ledger rows",
        "-----------",
        "",
        "*Measured* for the linear parity rows is ``100 max|gkx - ref| / max|ref|`` "
        "over the tracked scan, recomputed from the artifact. Reference ranks: "
        + "; ".join(f"{rank} {name}" for rank, name in RANKS.items())
        + ".",
        "",
    ]
    body = [
        (
            f"``{row['id']}``",
            _escape(row["claim"]),
            _measured(row, root),
            f"{_escape(row['reference'])} (rank {row['reference_rank']})",
            row["status"],
            f"``{row['artifact']}``",
        )
        for row in rows
    ]
    out += _table(
        ("ID", "Claim", "Measured", "Reference (rank)", "Status", "Artifact"),
        "12 18 16 26 8 20",
        body,
    )

    noted = [row for row in rows if row.get("notes")]
    if noted:
        out += ["Row notes", "---------", ""]
        for row in noted:
            out.append(f"- ``{row['id']}`` ({row['status']}): {_escape(row['notes'])}")
        out.append("")

    linear = [row for row in rows if str(row["id"]).startswith("L-lin-")]
    if linear:
        out += [
            "Velocity-space regularization of the linear rows",
            "------------------------------------------------",
            "",
            "Each linear row declares the velocity-space dissipation its deck ran with. "
            "A row without a Laguerre-space channel also states whether its growth rate "
            "is converged in velocity resolution.",
            "",
        ]
        out += _table(
            ("ID", "Regularization", "Velocity limit", "Evidence"),
            "18 22 14 46",
            [
                (
                    f"``{row['id']}``",
                    ", ".join(f"``{name}``" for name in row["velocity_regularization"]),
                    row.get("velocity_limit", "--"),
                    _escape(row.get("velocity_limit_evidence", "--")),
                )
                for row in linear
            ],
        )
    out.append(END)
    return "\n".join(out)


def splice(page_text: str, block: str) -> str:
    """Replace the marked block of ``page_text`` with ``block``."""

    start = page_text.index(BEGIN)
    stop = page_text.index(END, start) + len(END)
    return page_text[:start] + block + page_text[stop:]


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument(
        "--check", action="store_true", help="fail if the page is stale"
    )
    args = parser.parse_args(argv)
    current = PAGE.read_text(encoding="utf-8")
    expected = splice(current, render())
    if args.check:
        if current != expected:
            print(
                f"{PAGE.relative_to(ROOT)} is stale; run python scripts/validation_matrix.py"
            )
            return 1
        return 0
    PAGE.write_text(expected, encoding="utf-8")
    return 0


if __name__ == "__main__":
    sys.exit(main())
